### ISSUE TITLE
Package is blocked by uBlock Origin

### ISSUE THREAD

**Issue by klaussner** [meteor-svelte/svelte-tracker#2]
The `svelte_tracker.js` file is blocked by uBlock Origin (`net::ERR_BLOCKED_BY_CLIENT`) when Meteor runs in development mode. Maybe that's because of the file name? Meteor's `tracker.js` isn't blocked, though… :thinking: As a workaround, I added `localhost` to my uBlock Origin whitelist.

![svelte-tracker-blocked](https://user-images.githubusercontent.com/1312807/35776406-1dfadef6-099c-11e8-9473-be6c5306e464.png)

**Comment by zimme** [comment]
I guess it's good practice to unblock your development server. Could be a problem if anyone is running `meteor run` as a prod server.

**Comment by zimme** [comment]
I wonder if this happens in production when using dynamic import.

**Comment by klaussner** [comment]
Apparently, URLs are blocked if they include the word `tracker` and a query (e.g., `?hash=xyz`), so it should work if JavaScript is bundled and minified. Dynamically importing the package also works (after I made [this change](https://github.com/meteor-svelte/svelte-tracker/commit/151d651e6b0c82d9832a30c870c7bb98573fe509)) because the file name isn't included in the URL.

**Comment by klaussner** [comment]
Nothing to do here. :slightly_smiling_face:
